<?php

/**
 *
 * @file
 * Primary module hooks for layoutscommerce module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_entity_type_build().
 */
function layoutscommerce_entity_type_build(array &$entity_types) {
  $entity_types['commerce_order_item']->setFormClass('add_to_cart_flat', '\Drupal\layoutscommerce\Form\AddToCartFormFlat');
}

/**
 * Implements hook_theme().
 */
function layoutscommerce_theme() {
  //
  $hooks['layoutscommerce_product_teaser_view_style'] = [
    'preprocess functions' => [
      'template_preprocess_layoutscommerce_product_teaser_view_style'
    ],
    'file' => 'layoutscommerce.theme.inc'
  ];
  //
  $hooks['layoutscommerce_attribute_items'] = [
    'variables' => [
      'price' => NULL,
      'small_info' => NULL,
      'options' => NULL,
      'items' => NULL,
      'currency' => NULL
    ],
    'preprocess functions' => [
      'template_preprocess_layoutscommerce_attribute_items'
    ],
    'file' => 'layoutscommerce.theme.inc'
  ];
  //
  $hooks['layoutscommerce_comments'] = [
    'variables' => [
      'avis' => NULL,
      'notes' => NULL,
      'comments' => NULL,
      'comment_form' => NULL
    ],
    'preprocess functions' => [
      'template_preprocess_layoutscommerce_comments'
    ],
    'file' => 'layoutscommerce.theme.inc'
  ];
  //
  $hooks['layoutscommerce_price_calculated'] = [
    'variables' => [
      'calculated_price' => NULL,
      'purchasable_entity' => NULL,
      'currency_code' => NULL,
      'duration' => NULL,
      'content_class' => NULL,
      'symbol_class' => NULL,
      'price_class' => NULL,
      'duration_class' => NULL
    ],
    'preprocess functions' => [
      'template_layoutscommerce_price_calculated'
    ]
  ];
  $hooks['layoutscommerce_badge'] = [
    'variables' => [
      'value' => NULL,
      'value_class' => NULL
    ]
  ];
  return $hooks;
}

function template_layoutscommerce_price_calculated(&$vars) {
  //
}


